# Generated by Django 3.2.7 on 2021-10-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='qubntity',
            new_name='quantity',
        ),
    ]
