# Generated by Django 3.2.7 on 2021-10-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='имя')),
                ('numbers', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='имеил')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
